# fly.toml app configuration file generated for survivors on 2025-02-07T17:32:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "survivors"
primary_region = "waw"


[env]

[build]

[[services]]
  # This is the internal port your app listens on.
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  

  [services.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

  # Expose port 80 for HTTP (optional: you can redirect these to HTTPS)
  [[services.ports]]
    port = 80
    handlers = ["http"]

  # Expose port 443 for HTTPS; TLS termination here supports wss:// connections.
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 8080
    handlers = ["tls", "http"]

  # Optional health check endpoint – adjust the path if necessary.
  [[services.http_checks]]
    grace_period = "5s"
    path = "/health"
    interval = "10s"  # in milliseconds
    timeout = "2s"    # in milliseconds


[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
